name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: zhaoxiuya
          plugin_languages: yes
          plugin_languages_sections: most-used
          plugin_languages_limit: 12
          plugin_languages_ignored: "Jupyter Notebook, HTML"
          plugin_languages_indepth: yes
          plugin_languages_details: lines, percentage
          commits_authoring: >
            zhaoxiuya
            zhaoxiuya@users.noreply.github.com
            

